### ISSUE TITLE
textlintを使いやすく配置したい

### ISSUE THREAD

**Issue by saucer-jp** [nakajmg/cgmd-browser#1]
- 機能自体の実行方法を考える
- どのように表記間違いを表示するかを考える
- 実行と表示をどこに配置するかを考える

**Comment by saucer-jp** [comment]
@nakajmg 技術的に可能か不可能かよくわからないので、こんなんだったらいいな〜というレベルで考えてみました。

概要としては、右上のアイコンをactiveにすると、textlintにマッチした文字列がハイライトされます。それとtextlintが起動中は右パネル（パネルでなくてもよいかも…）が展開して内訳が閲覧できるのと、該当箇所にジャンプできるとか。

![image](https://cloud.githubusercontent.com/assets/710479/19128751/a7c44efc-8b7f-11e6-953f-c1e6db4148c5.png)

**Comment by nakajmg** [comment]
ありがとうございます :ok_man: 
- マッチした文字列のハイライト
  - https://markjs.io/ でできそう
- 右パネルで閲覧
  - 可能
- 該当箇所にジャンプ
  - 技術的に無理そう（lintかけるのは.mdなので描画されてるHTML内の文章と1:1の対応ができない
  - （ジャンプしてもアプリ側で編集できるわけじゃないので二度手間になりそう

lintの結果に n行目のn文字目 の情報があるので同じ表記ゆれまとめてしまうとその辺の情報が落ちちゃうのかな〜と思うのですが、ラベルクリックしたらリストがびよーんと伸びて該当箇所の情報が一覧できる、とかでもよさそう

**Comment by saucer-jp** [comment]
> 技術的に無理そう（lintかけるのは.mdなので描画されてるHTML内の文章と1:1の対応ができない

ほうほう。了解〜

> lintの結果に n行目のn文字目 の情報があるので同じ表記ゆれまとめてしまうとその辺の情報が落ちちゃうのかな〜と思うのですが、ラベルクリックしたらリストがびよーんと伸びて該当箇所の情報が一覧できる、とかでもよさそう

ジャンプの機能なくなるし、そうしたらラベルクリックで詳細びよーん良さそう。

**Comment by nakajmg** [comment]
こんな感じに 💁 

![image](https://cloud.githubusercontent.com/assets/1995370/19141363/bda16110-8bcf-11e6-8119-9eed26de7dcb.png)

**Comment by saucer-jp** [comment]
よさそ〜 👍

**Comment by nakajmg** [comment]
開いたワードをハイライトするように💁🏻

![image](https://cloud.githubusercontent.com/assets/1995370/19182372/d213089a-8cad-11e6-8293-23b4bbe0387f.png)

**Comment by nakajmg** [comment]
@saucer-jp 1.1.0に追加しました 🎉 

https://github.com/nakajmg/cgmd-browser/releases/tag/1.1.0
